fix: bump node image versions to 20-bullseye-slim
This fixes the Docker build after receiving broken changes from
renovate.

Docker build command:

	docker build --no-cache --file Dockerfile \
		--build-arg HTTPS_PROXY={$HTTPS_PROXY} \
		--build-arg HTTP_PROXY={$HTTP_PROXY} \
		--build-arg NO_PROXY={$NO_PROXY} \
		--build-arg NODE_EXTRA_CA_CERTS=proxy-cert.crt \
		.

Example build output before fix:

	 => ERROR [10/17] RUN npm ci
	------
	 > [10/17] RUN npm ci:
	...
	20.04 > nuxt-app@0.0.3 postinstall
	20.04 > nuxt prepare
	...
	20.95 ERROR Cannot find native binding.
		npm has a bug related to optional dependencies
		(https://github.com/npm/cli/issues/4828).
		Please try npm i again after removing both package-lock.json
		and node_modules directory.
	...
	20.95     code: 'MODULE_NOT_FOUND',
	...
	20.95   { Error: Cannot find module '@oxc-parser/binding-linux-x64-gnu'

Signed-off-by: Eric Thelin <extern.eric.thelin@digg.se>